# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

from __future__ import annotations

import math
import typing as T

import numpy

import sym


def measurement_model(
    X: numpy.ndarray, L: numpy.ndarray
) -> tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray]:
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        X: Matrix31
        L: Matrix41

    Outputs:
        z_pred: Matrix11
        H_X: Matrix13
        H_L: Matrix14
    """

    # Total ops: 30

    # Input arrays
    if X.shape == (3,):
        X = X.reshape((3, 1))
    elif X.shape != (3, 1):
        raise IndexError(
            "X is expected to have shape (3, 1) or (3,); instead had shape {}".format(X.shape)
        )

    if L.shape == (4,):
        L = L.reshape((4, 1))
    elif L.shape != (4, 1):
        raise IndexError(
            "L is expected to have shape (4, 1) or (4,); instead had shape {}".format(L.shape)
        )

    # Intermediate terms (15)
    _tmp0 = math.sin(L[2, 0])
    _tmp1 = L[1, 0] - X[1, 0]
    _tmp2 = L[3, 0] * _tmp1 + _tmp0
    _tmp3 = math.cos(L[2, 0])
    _tmp4 = L[0, 0] - X[0, 0]
    _tmp5 = L[3, 0] * _tmp4 + _tmp3
    _tmp6 = _tmp5
    _tmp7 = _tmp6**2
    _tmp8 = 1 / (_tmp2**2 + _tmp7)
    _tmp9 = L[3, 0] * _tmp8
    _tmp10 = _tmp2 * _tmp9
    _tmp11 = _tmp6 * _tmp9
    _tmp12 = 1 / _tmp6
    _tmp13 = _tmp2 / _tmp7
    _tmp14 = _tmp7 * _tmp8

    # Output terms
    _z_pred = numpy.zeros(1)
    _z_pred[0] = -X[2, 0] + math.atan2(_tmp2, _tmp6)
    _H_X = numpy.zeros(3)
    _H_X[0] = _tmp10
    _H_X[1] = -_tmp11
    _H_X[2] = -1
    _H_L = numpy.zeros(4)
    _H_L[0] = -_tmp10
    _H_L[1] = _tmp11
    _H_L[2] = _tmp14 * (_tmp0 * _tmp13 + _tmp12 * _tmp3)
    _H_L[3] = _tmp14 * (_tmp1 * _tmp12 - _tmp13 * _tmp4)
    return _z_pred, _H_X, _H_L
