# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

from __future__ import annotations

import math
import typing as T

import numpy

import sym


def process_model(
    X: numpy.ndarray, U: numpy.ndarray, dt: float
) -> tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray]:
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        X: Matrix31
        U: Matrix21
        dt: Scalar

    Outputs:
        X_next: Matrix31
        F: Matrix33
        W: Matrix32
    """

    # Total ops: 11

    # Input arrays
    if X.shape == (3,):
        X = X.reshape((3, 1))
    elif X.shape != (3, 1):
        raise IndexError(
            "X is expected to have shape (3, 1) or (3,); instead had shape {}".format(X.shape)
        )

    if U.shape == (2,):
        U = U.reshape((2, 1))
    elif U.shape != (2, 1):
        raise IndexError(
            "U is expected to have shape (2, 1) or (2,); instead had shape {}".format(U.shape)
        )

    # Intermediate terms (4)
    _tmp0 = dt * math.cos(X[2, 0])
    _tmp1 = U[0, 0] * _tmp0
    _tmp2 = dt * math.sin(X[2, 0])
    _tmp3 = U[0, 0] * _tmp2

    # Output terms
    _X_next = numpy.zeros(3)
    _X_next[0] = X[0, 0] + _tmp1
    _X_next[1] = X[1, 0] + _tmp3
    _X_next[2] = U[1, 0] * dt + X[2, 0]
    _F = numpy.zeros((3, 3))
    _F[0, 0] = 1
    _F[1, 0] = 0
    _F[2, 0] = 0
    _F[0, 1] = 0
    _F[1, 1] = 1
    _F[2, 1] = 0
    _F[0, 2] = -_tmp3
    _F[1, 2] = _tmp1
    _F[2, 2] = 1
    _W = numpy.zeros((3, 2))
    _W[0, 0] = _tmp0
    _W[1, 0] = _tmp2
    _W[2, 0] = 0
    _W[0, 1] = 0
    _W[1, 1] = 0
    _W[2, 1] = dt
    return _X_next, _F, _W
