// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym {

/**
 * This function was autogenerated. Do not modify by hand.
 *
 * Args:
 *     X: Matrix31
 *     U: Matrix21
 *     dt: Scalar
 *
 * Outputs:
 *     X_next: Matrix31
 *     F: Matrix33
 *     W: Matrix32
 */
template <typename Scalar>
void ProcessModel(const Eigen::Matrix<Scalar, 3, 1>& X, const Eigen::Matrix<Scalar, 2, 1>& U,
                  const Scalar dt, Eigen::Matrix<Scalar, 3, 1>* const X_next = nullptr,
                  Eigen::Matrix<Scalar, 3, 3>* const F = nullptr,
                  Eigen::Matrix<Scalar, 3, 2>* const W = nullptr) {
  // Total ops: 11

  // Input arrays

  // Intermediate terms (4)
  const Scalar _tmp0 = dt * std::cos(X(2, 0));
  const Scalar _tmp1 = U(0, 0) * _tmp0;
  const Scalar _tmp2 = dt * std::sin(X(2, 0));
  const Scalar _tmp3 = U(0, 0) * _tmp2;

  // Output terms (3)
  if (X_next != nullptr) {
    Eigen::Matrix<Scalar, 3, 1>& _X_next = (*X_next);

    _X_next(0, 0) = X(0, 0) + _tmp1;
    _X_next(1, 0) = X(1, 0) + _tmp3;
    _X_next(2, 0) = U(1, 0) * dt + X(2, 0);
  }

  if (F != nullptr) {
    Eigen::Matrix<Scalar, 3, 3>& _F = (*F);

    _F(0, 0) = 1;
    _F(1, 0) = 0;
    _F(2, 0) = 0;
    _F(0, 1) = 0;
    _F(1, 1) = 1;
    _F(2, 1) = 0;
    _F(0, 2) = -_tmp3;
    _F(1, 2) = _tmp1;
    _F(2, 2) = 1;
  }

  if (W != nullptr) {
    Eigen::Matrix<Scalar, 3, 2>& _W = (*W);

    _W(0, 0) = _tmp0;
    _W(1, 0) = _tmp2;
    _W(2, 0) = 0;
    _W(0, 1) = 0;
    _W(1, 1) = 0;
    _W(2, 1) = dt;
  }
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
