# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

from __future__ import annotations

import math
import typing as T

import numpy

import sym


def landmark_initialization_jacobian(
    S: numpy.ndarray, u: float, v: float, rho: float, u0: float, v0: float, f: float, epsilon: float
) -> tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray]:
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        S: Matrix13_1
        u: Scalar
        v: Scalar
        rho: Scalar
        u0: Scalar
        v0: Scalar
        f: Scalar
        epsilon: Scalar

    Outputs:
        Gr: Matrix6_13
        Gy: Matrix62
        Gs: Matrix61
    """

    # Total ops: 172

    # Input arrays
    if S.shape == (13,):
        S = S.reshape((13, 1))
    elif S.shape != (13, 1):
        raise IndexError(
            "S is expected to have shape (13, 1) or (13,); instead had shape {}".format(S.shape)
        )

    # Intermediate terms (64)
    _tmp0 = 2 * S[6, 0]
    _tmp1 = 2 * S[4, 0]
    _tmp2 = 1 / f
    _tmp3 = _tmp2 * (u - u0)
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = 4 * S[3, 0]
    _tmp6 = _tmp2 * (v - v0)
    _tmp7 = -_tmp0 + _tmp4 - _tmp5 * _tmp6
    _tmp8 = S[3, 0] * _tmp0
    _tmp9 = 2 * S[5, 0]
    _tmp10 = S[4, 0] * _tmp9
    _tmp11 = -2 * S[3, 0] ** 2
    _tmp12 = 1 - 2 * S[5, 0] ** 2
    _tmp13 = _tmp11 + _tmp12
    _tmp14 = S[5, 0] * _tmp0
    _tmp15 = S[3, 0] * _tmp1
    _tmp16 = _tmp14 + _tmp15
    _tmp17 = _tmp10 + _tmp13 * _tmp6 + _tmp16 * _tmp3 - _tmp8
    _tmp18 = 2 * _tmp17
    _tmp19 = _tmp1 * _tmp6
    _tmp20 = _tmp19 + _tmp9
    _tmp21 = S[4, 0] * _tmp0
    _tmp22 = S[3, 0] * _tmp9
    _tmp23 = -2 * S[4, 0] ** 2
    _tmp24 = _tmp12 + _tmp23
    _tmp25 = -_tmp14 + _tmp15
    _tmp26 = _tmp21 + _tmp22 + _tmp24 * _tmp3 + _tmp25 * _tmp6
    _tmp27 = 2 * _tmp26
    _tmp28 = _tmp17**2
    _tmp29 = _tmp26**2 + _tmp28
    _tmp30 = math.sqrt(_tmp29)
    _tmp31 = _tmp10 + _tmp8
    _tmp32 = -_tmp21 + _tmp22
    _tmp33 = _tmp11 + _tmp23 + _tmp3 * _tmp32 + _tmp31 * _tmp6 + 1
    _tmp34 = _tmp33 + math.copysign(epsilon, _tmp33)
    _tmp35 = (1.0 / 2.0) / (_tmp30 * _tmp34)
    _tmp36 = _tmp0 * _tmp6
    _tmp37 = _tmp3 * _tmp9
    _tmp38 = _tmp34**2
    _tmp39 = _tmp30 / _tmp38
    _tmp40 = _tmp38 / (_tmp29 + _tmp38)
    _tmp41 = _tmp26 + math.copysign(epsilon, _tmp26)
    _tmp42 = 1 / _tmp41
    _tmp43 = _tmp41**2
    _tmp44 = _tmp17 / _tmp43
    _tmp45 = _tmp43 / (_tmp28 + _tmp43)
    _tmp46 = 4 * S[4, 0]
    _tmp47 = 2 * S[3, 0]
    _tmp48 = _tmp47 * _tmp6
    _tmp49 = _tmp0 - _tmp3 * _tmp46 + _tmp48
    _tmp50 = _tmp3 * _tmp47
    _tmp51 = _tmp50 + _tmp9
    _tmp52 = _tmp0 * _tmp3
    _tmp53 = _tmp6 * _tmp9
    _tmp54 = 4 * S[5, 0]
    _tmp55 = _tmp1 + _tmp52 - _tmp54 * _tmp6
    _tmp56 = -_tmp3 * _tmp54 - _tmp36 + _tmp47
    _tmp57 = _tmp37 - _tmp47
    _tmp58 = _tmp1 - _tmp53
    _tmp59 = _tmp2 * _tmp27
    _tmp60 = _tmp18 * _tmp2
    _tmp61 = _tmp2 * _tmp39
    _tmp62 = _tmp2 * _tmp44
    _tmp63 = _tmp2 * _tmp42

    # Output terms
    _Gr = numpy.zeros((6, 13))
    _Gr[0, 0] = 1
    _Gr[1, 0] = 0
    _Gr[2, 0] = 0
    _Gr[3, 0] = 0
    _Gr[4, 0] = 0
    _Gr[5, 0] = 0
    _Gr[0, 1] = 0
    _Gr[1, 1] = 1
    _Gr[2, 1] = 0
    _Gr[3, 1] = 0
    _Gr[4, 1] = 0
    _Gr[5, 1] = 0
    _Gr[0, 2] = 0
    _Gr[1, 2] = 0
    _Gr[2, 2] = 1
    _Gr[3, 2] = 0
    _Gr[4, 2] = 0
    _Gr[5, 2] = 0
    _Gr[0, 3] = 0
    _Gr[1, 3] = 0
    _Gr[2, 3] = 0
    _Gr[3, 3] = _tmp40 * (
        _tmp35 * (_tmp18 * _tmp7 + _tmp20 * _tmp27) - _tmp39 * (_tmp36 + _tmp37 - _tmp5)
    )
    _Gr[4, 3] = _tmp45 * (-_tmp20 * _tmp44 + _tmp42 * _tmp7)
    _Gr[5, 3] = 0
    _Gr[0, 4] = 0
    _Gr[1, 4] = 0
    _Gr[2, 4] = 0
    _Gr[3, 4] = _tmp40 * (
        _tmp35 * (_tmp18 * _tmp51 + _tmp27 * _tmp49) - _tmp39 * (-_tmp46 - _tmp52 + _tmp53)
    )
    _Gr[4, 4] = _tmp45 * (_tmp42 * _tmp51 - _tmp44 * _tmp49)
    _Gr[5, 4] = 0
    _Gr[0, 5] = 0
    _Gr[1, 5] = 0
    _Gr[2, 5] = 0
    _Gr[3, 5] = _tmp40 * (_tmp35 * (_tmp18 * _tmp55 + _tmp27 * _tmp56) - _tmp39 * (_tmp19 + _tmp50))
    _Gr[4, 5] = _tmp45 * (_tmp42 * _tmp55 - _tmp44 * _tmp56)
    _Gr[5, 5] = 0
    _Gr[0, 6] = 0
    _Gr[1, 6] = 0
    _Gr[2, 6] = 0
    _Gr[3, 6] = _tmp40 * (_tmp35 * (_tmp18 * _tmp57 + _tmp27 * _tmp58) - _tmp39 * (-_tmp4 + _tmp48))
    _Gr[4, 6] = _tmp45 * (_tmp42 * _tmp57 - _tmp44 * _tmp58)
    _Gr[5, 6] = 0
    _Gr[0, 7] = 0
    _Gr[1, 7] = 0
    _Gr[2, 7] = 0
    _Gr[3, 7] = 0
    _Gr[4, 7] = 0
    _Gr[5, 7] = 0
    _Gr[0, 8] = 0
    _Gr[1, 8] = 0
    _Gr[2, 8] = 0
    _Gr[3, 8] = 0
    _Gr[4, 8] = 0
    _Gr[5, 8] = 0
    _Gr[0, 9] = 0
    _Gr[1, 9] = 0
    _Gr[2, 9] = 0
    _Gr[3, 9] = 0
    _Gr[4, 9] = 0
    _Gr[5, 9] = 0
    _Gr[0, 10] = 0
    _Gr[1, 10] = 0
    _Gr[2, 10] = 0
    _Gr[3, 10] = 0
    _Gr[4, 10] = 0
    _Gr[5, 10] = 0
    _Gr[0, 11] = 0
    _Gr[1, 11] = 0
    _Gr[2, 11] = 0
    _Gr[3, 11] = 0
    _Gr[4, 11] = 0
    _Gr[5, 11] = 0
    _Gr[0, 12] = 0
    _Gr[1, 12] = 0
    _Gr[2, 12] = 0
    _Gr[3, 12] = 0
    _Gr[4, 12] = 0
    _Gr[5, 12] = 0
    _Gy = numpy.zeros((6, 2))
    _Gy[0, 0] = 0
    _Gy[1, 0] = 0
    _Gy[2, 0] = 0
    _Gy[3, 0] = _tmp40 * (-_tmp32 * _tmp61 + _tmp35 * (_tmp16 * _tmp60 + _tmp24 * _tmp59))
    _Gy[4, 0] = _tmp45 * (_tmp16 * _tmp63 - _tmp24 * _tmp62)
    _Gy[5, 0] = 0
    _Gy[0, 1] = 0
    _Gy[1, 1] = 0
    _Gy[2, 1] = 0
    _Gy[3, 1] = _tmp40 * (-_tmp31 * _tmp61 + _tmp35 * (_tmp13 * _tmp60 + _tmp25 * _tmp59))
    _Gy[4, 1] = _tmp45 * (_tmp13 * _tmp63 - _tmp25 * _tmp62)
    _Gy[5, 1] = 0
    _Gs = numpy.zeros(6)
    _Gs[0] = 0
    _Gs[1] = 0
    _Gs[2] = 0
    _Gs[3] = 0
    _Gs[4] = 0
    _Gs[5] = 1
    return _Gr, _Gy, _Gs
