# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

from __future__ import annotations

import math
import typing as T

import numpy

import sym


def landmark_measurement(
    S: numpy.ndarray,
    f: float,
    dx: float,
    dy: float,
    u0: float,
    v0: float,
    xi_l: float,
    yi_l: float,
    zi_l: float,
    theta_l: float,
    phi_l: float,
    rho_l: float,
) -> numpy.ndarray:
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        S: Matrix13_1
        f: Scalar
        dx: Scalar
        dy: Scalar
        u0: Scalar
        v0: Scalar
        xi_l: Scalar
        yi_l: Scalar
        zi_l: Scalar
        theta_l: Scalar
        phi_l: Scalar
        rho_l: Scalar

    Outputs:
        h: Matrix21
    """

    # Total ops: 65

    # Input arrays
    if S.shape == (13,):
        S = S.reshape((13, 1))
    elif S.shape != (13, 1):
        raise IndexError(
            "S is expected to have shape (13, 1) or (13,); instead had shape {}".format(S.shape)
        )

    # Intermediate terms (17)
    _tmp0 = -2 * S[4, 0] ** 2
    _tmp1 = 1 - 2 * S[5, 0] ** 2
    _tmp2 = 1 / rho_l
    _tmp3 = _tmp2 * math.sin(theta_l)
    _tmp4 = -S[0, 0] + _tmp3 * math.cos(phi_l) + xi_l
    _tmp5 = 2 * S[6, 0]
    _tmp6 = S[5, 0] * _tmp5
    _tmp7 = 2 * S[3, 0] * S[4, 0]
    _tmp8 = -S[1, 0] + _tmp3 * math.sin(phi_l) + yi_l
    _tmp9 = S[4, 0] * _tmp5
    _tmp10 = 2 * S[5, 0]
    _tmp11 = S[3, 0] * _tmp10
    _tmp12 = -S[2, 0] + _tmp2 * math.cos(theta_l) + zi_l
    _tmp13 = S[3, 0] * _tmp5
    _tmp14 = S[4, 0] * _tmp10
    _tmp15 = -2 * S[3, 0] ** 2
    _tmp16 = f / (
        _tmp12 * (_tmp0 + _tmp15 + 1) + _tmp4 * (_tmp11 + _tmp9) + _tmp8 * (-_tmp13 + _tmp14)
    )

    # Output terms
    _h = numpy.zeros(2)
    _h[0] = (
        _tmp16
        * (_tmp12 * (_tmp11 - _tmp9) + _tmp4 * (_tmp0 + _tmp1) + _tmp8 * (_tmp6 + _tmp7))
        / dx
        + u0
    )
    _h[1] = (
        _tmp16
        * (_tmp12 * (_tmp13 + _tmp14) + _tmp4 * (-_tmp6 + _tmp7) + _tmp8 * (_tmp1 + _tmp15))
        / dy
        + v0
    )
    return _h
