# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

from __future__ import annotations

import math
import typing as T

import numpy

import sym


def landmark_initialization(
    S: numpy.ndarray, u: float, v: float, rho: float, u0: float, v0: float, f: float, epsilon: float
) -> numpy.ndarray:
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        S: Matrix13_1
        u: Scalar
        v: Scalar
        rho: Scalar
        u0: Scalar
        v0: Scalar
        f: Scalar
        epsilon: Scalar

    Outputs:
        Y_l_init: Matrix61
    """

    # Total ops: 55

    # Input arrays
    if S.shape == (13,):
        S = S.reshape((13, 1))
    elif S.shape != (13, 1):
        raise IndexError(
            "S is expected to have shape (13, 1) or (13,); instead had shape {}".format(S.shape)
        )

    # Intermediate terms (17)
    _tmp0 = 2 * S[6, 0]
    _tmp1 = S[4, 0] * _tmp0
    _tmp2 = 2 * S[5, 0]
    _tmp3 = S[3, 0] * _tmp2
    _tmp4 = -2 * S[4, 0] ** 2
    _tmp5 = 1 - 2 * S[5, 0] ** 2
    _tmp6 = 1 / f
    _tmp7 = _tmp6 * (u - u0)
    _tmp8 = S[5, 0] * _tmp0
    _tmp9 = 2 * S[3, 0] * S[4, 0]
    _tmp10 = _tmp6 * (v - v0)
    _tmp11 = _tmp1 + _tmp10 * (-_tmp8 + _tmp9) + _tmp3 + _tmp7 * (_tmp4 + _tmp5)
    _tmp12 = S[3, 0] * _tmp0
    _tmp13 = S[4, 0] * _tmp2
    _tmp14 = -2 * S[3, 0] ** 2
    _tmp15 = _tmp10 * (_tmp14 + _tmp5) - _tmp12 + _tmp13 + _tmp7 * (_tmp8 + _tmp9)
    _tmp16 = _tmp10 * (_tmp12 + _tmp13) + _tmp14 + _tmp4 + _tmp7 * (-_tmp1 + _tmp3) + 1

    # Output terms
    _Y_l_init = numpy.zeros(6)
    _Y_l_init[0] = S[0, 0]
    _Y_l_init[1] = S[1, 0]
    _Y_l_init[2] = S[2, 0]
    _Y_l_init[3] = math.atan2(
        math.sqrt(_tmp11**2 + _tmp15**2), _tmp16 + math.copysign(epsilon, _tmp16)
    )
    _Y_l_init[4] = math.atan2(_tmp15, _tmp11 + math.copysign(epsilon, _tmp11))
    _Y_l_init[5] = rho
    return _Y_l_init
