# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

from __future__ import annotations

import math
import typing as T

import numpy

import sym


def landmark_measurement_jacobian(
    S: numpy.ndarray,
    f: float,
    dx: float,
    dy: float,
    u0: float,
    v0: float,
    xi_l: float,
    yi_l: float,
    zi_l: float,
    theta_l: float,
    phi_l: float,
    rho_l: float,
) -> tuple[numpy.ndarray, numpy.ndarray]:
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        S: Matrix13_1
        f: Scalar
        dx: Scalar
        dy: Scalar
        u0: Scalar
        v0: Scalar
        xi_l: Scalar
        yi_l: Scalar
        zi_l: Scalar
        theta_l: Scalar
        phi_l: Scalar
        rho_l: Scalar

    Outputs:
        Hr: Matrix2_13
        Hl: Matrix26
    """

    # Total ops: 228

    # Input arrays
    if S.shape == (13,):
        S = S.reshape((13, 1))
    elif S.shape != (13, 1):
        raise IndexError(
            "S is expected to have shape (13, 1) or (13,); instead had shape {}".format(S.shape)
        )

    # Intermediate terms (88)
    _tmp0 = 2 * S[6, 0]
    _tmp1 = S[4, 0] * _tmp0
    _tmp2 = 2 * S[3, 0]
    _tmp3 = S[5, 0] * _tmp2
    _tmp4 = _tmp1 + _tmp3
    _tmp5 = math.cos(phi_l)
    _tmp6 = 1 / rho_l
    _tmp7 = math.sin(theta_l)
    _tmp8 = _tmp6 * _tmp7
    _tmp9 = _tmp5 * _tmp8
    _tmp10 = -S[0, 0] + _tmp9 + xi_l
    _tmp11 = S[3, 0] * _tmp0
    _tmp12 = 2 * S[4, 0] * S[5, 0]
    _tmp13 = -_tmp11 + _tmp12
    _tmp14 = math.sin(phi_l)
    _tmp15 = _tmp14 * _tmp8
    _tmp16 = -S[1, 0] + _tmp15 + yi_l
    _tmp17 = -2 * S[4, 0] ** 2
    _tmp18 = -2 * S[3, 0] ** 2
    _tmp19 = _tmp17 + _tmp18 + 1
    _tmp20 = math.cos(theta_l)
    _tmp21 = _tmp20 * _tmp6
    _tmp22 = -S[2, 0] + _tmp21 + zi_l
    _tmp23 = _tmp10 * _tmp4 + _tmp13 * _tmp16 + _tmp19 * _tmp22
    _tmp24 = f / _tmp23**2
    _tmp25 = 1 / dx
    _tmp26 = 1 - 2 * S[5, 0] ** 2
    _tmp27 = _tmp17 + _tmp26
    _tmp28 = S[5, 0] * _tmp0
    _tmp29 = S[4, 0] * _tmp2
    _tmp30 = _tmp28 + _tmp29
    _tmp31 = -_tmp1 + _tmp3
    _tmp32 = _tmp25 * (_tmp10 * _tmp27 + _tmp16 * _tmp30 + _tmp22 * _tmp31)
    _tmp33 = _tmp24 * _tmp32
    _tmp34 = _tmp33 * _tmp4
    _tmp35 = f / _tmp23
    _tmp36 = _tmp25 * _tmp35
    _tmp37 = _tmp27 * _tmp36
    _tmp38 = -_tmp28 + _tmp29
    _tmp39 = 1 / dy
    _tmp40 = _tmp35 * _tmp39
    _tmp41 = _tmp38 * _tmp40
    _tmp42 = _tmp18 + _tmp26
    _tmp43 = _tmp11 + _tmp12
    _tmp44 = _tmp39 * (_tmp10 * _tmp38 + _tmp16 * _tmp42 + _tmp22 * _tmp43)
    _tmp45 = _tmp24 * _tmp44
    _tmp46 = _tmp4 * _tmp45
    _tmp47 = _tmp30 * _tmp36
    _tmp48 = _tmp13 * _tmp33
    _tmp49 = _tmp13 * _tmp45
    _tmp50 = _tmp40 * _tmp42
    _tmp51 = _tmp19 * _tmp33
    _tmp52 = _tmp31 * _tmp36
    _tmp53 = _tmp19 * _tmp45
    _tmp54 = _tmp40 * _tmp43
    _tmp55 = 2 * _tmp16
    _tmp56 = S[4, 0] * _tmp55
    _tmp57 = 2 * _tmp22
    _tmp58 = S[5, 0] * _tmp57
    _tmp59 = _tmp0 * _tmp16
    _tmp60 = 2 * _tmp10
    _tmp61 = S[5, 0] * _tmp60
    _tmp62 = 4 * S[3, 0]
    _tmp63 = _tmp24 * (-_tmp22 * _tmp62 - _tmp59 + _tmp61)
    _tmp64 = S[4, 0] * _tmp60
    _tmp65 = _tmp0 * _tmp22
    _tmp66 = S[3, 0] * _tmp55
    _tmp67 = 4 * S[4, 0]
    _tmp68 = S[5, 0] * _tmp55
    _tmp69 = _tmp0 * _tmp10
    _tmp70 = -_tmp22 * _tmp67 + _tmp68 + _tmp69
    _tmp71 = S[3, 0] * _tmp60
    _tmp72 = _tmp56 + _tmp71
    _tmp73 = 4 * S[5, 0]
    _tmp74 = S[3, 0] * _tmp57
    _tmp75 = S[4, 0] * _tmp57
    _tmp76 = _tmp64 - _tmp66
    _tmp77 = _tmp4 * _tmp5
    _tmp78 = _tmp14 * _tmp21
    _tmp79 = _tmp13 * _tmp78 - _tmp19 * _tmp8 + _tmp21 * _tmp77
    _tmp80 = _tmp27 * _tmp5
    _tmp81 = _tmp38 * _tmp5
    _tmp82 = _tmp13 * _tmp9 - _tmp15 * _tmp4
    _tmp83 = rho_l ** (-2)
    _tmp84 = _tmp7 * _tmp83
    _tmp85 = _tmp14 * _tmp84
    _tmp86 = _tmp20 * _tmp83
    _tmp87 = -_tmp13 * _tmp85 - _tmp19 * _tmp86 - _tmp77 * _tmp84

    # Output terms
    _Hr = numpy.zeros((2, 13))
    _Hr[0, 0] = _tmp34 - _tmp37
    _Hr[1, 0] = -_tmp41 + _tmp46
    _Hr[0, 1] = -_tmp47 + _tmp48
    _Hr[1, 1] = _tmp49 - _tmp50
    _Hr[0, 2] = _tmp51 - _tmp52
    _Hr[1, 2] = _tmp53 - _tmp54
    _Hr[0, 3] = -_tmp32 * _tmp63 + _tmp36 * (_tmp56 + _tmp58)
    _Hr[1, 3] = _tmp40 * (-_tmp16 * _tmp62 + _tmp64 + _tmp65) - _tmp44 * _tmp63
    _Hr[0, 4] = -_tmp33 * _tmp70 + _tmp36 * (-_tmp10 * _tmp67 - _tmp65 + _tmp66)
    _Hr[1, 4] = _tmp40 * (_tmp58 + _tmp71) - _tmp45 * _tmp70
    _Hr[0, 5] = -_tmp33 * _tmp72 + _tmp36 * (-_tmp10 * _tmp73 + _tmp59 + _tmp74)
    _Hr[1, 5] = _tmp40 * (-_tmp16 * _tmp73 - _tmp69 + _tmp75) - _tmp45 * _tmp72
    _Hr[0, 6] = -_tmp33 * _tmp76 + _tmp36 * (_tmp68 - _tmp75)
    _Hr[1, 6] = _tmp40 * (-_tmp61 + _tmp74) - _tmp45 * _tmp76
    _Hr[0, 7] = 0
    _Hr[1, 7] = 0
    _Hr[0, 8] = 0
    _Hr[1, 8] = 0
    _Hr[0, 9] = 0
    _Hr[1, 9] = 0
    _Hr[0, 10] = 0
    _Hr[1, 10] = 0
    _Hr[0, 11] = 0
    _Hr[1, 11] = 0
    _Hr[0, 12] = 0
    _Hr[1, 12] = 0
    _Hl = numpy.zeros((2, 6))
    _Hl[0, 0] = -_tmp34 + _tmp37
    _Hl[1, 0] = _tmp41 - _tmp46
    _Hl[0, 1] = _tmp47 - _tmp48
    _Hl[1, 1] = -_tmp49 + _tmp50
    _Hl[0, 2] = -_tmp51 + _tmp52
    _Hl[1, 2] = -_tmp53 + _tmp54
    _Hl[0, 3] = -_tmp33 * _tmp79 + _tmp36 * (_tmp21 * _tmp80 + _tmp30 * _tmp78 - _tmp31 * _tmp8)
    _Hl[1, 3] = _tmp40 * (_tmp21 * _tmp81 + _tmp42 * _tmp78 - _tmp43 * _tmp8) - _tmp45 * _tmp79
    _Hl[0, 4] = -_tmp33 * _tmp82 + _tmp36 * (-_tmp15 * _tmp27 + _tmp30 * _tmp9)
    _Hl[1, 4] = _tmp40 * (-_tmp15 * _tmp38 + _tmp42 * _tmp9) - _tmp45 * _tmp82
    _Hl[0, 5] = -_tmp33 * _tmp87 + _tmp36 * (-_tmp30 * _tmp85 - _tmp31 * _tmp86 - _tmp80 * _tmp84)
    _Hl[1, 5] = _tmp40 * (-_tmp42 * _tmp85 - _tmp43 * _tmp86 - _tmp81 * _tmp84) - _tmp45 * _tmp87
    return _Hr, _Hl
