# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

from __future__ import annotations

import math
import typing as T

import numpy

import sym


def robot_state_update(
    S: numpy.ndarray,
    ax_n: float,
    ay_n: float,
    az_n: float,
    gx_n: float,
    gy_n: float,
    gz_n: float,
    dt: float,
    epsilon: float,
) -> numpy.ndarray:
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        S: Matrix13_1
        ax_n: Scalar
        ay_n: Scalar
        az_n: Scalar
        gx_n: Scalar
        gy_n: Scalar
        gz_n: Scalar
        dt: Scalar
        epsilon: Scalar

    Outputs:
        Snext: Matrix13_1
    """

    # Total ops: 67

    # Input arrays
    if S.shape == (13,):
        S = S.reshape((13, 1))
    elif S.shape != (13, 1):
        raise IndexError(
            "S is expected to have shape (13, 1) or (13,); instead had shape {}".format(S.shape)
        )

    # Intermediate terms (15)
    _tmp0 = S[7, 0] + ax_n * dt
    _tmp1 = S[8, 0] + ay_n * dt
    _tmp2 = S[9, 0] + az_n * dt
    _tmp3 = S[12, 0] + dt * gz_n
    _tmp4 = dt**2
    _tmp5 = S[10, 0] + dt * gx_n
    _tmp6 = S[11, 0] + dt * gy_n
    _tmp7 = math.sqrt(_tmp3**2 * _tmp4 + _tmp4 * _tmp5**2 + _tmp4 * _tmp6**2 + epsilon**2)
    _tmp8 = (1.0 / 2.0) * _tmp7
    _tmp9 = dt * math.sin(_tmp8) / _tmp7
    _tmp10 = S[4, 0] * _tmp9
    _tmp11 = math.cos(_tmp8)
    _tmp12 = S[5, 0] * _tmp9
    _tmp13 = S[6, 0] * _tmp9
    _tmp14 = S[3, 0] * _tmp9

    # Output terms
    _Snext = numpy.zeros(13)
    _Snext[0] = S[0, 0] + _tmp0 * dt
    _Snext[1] = S[1, 0] + _tmp1 * dt
    _Snext[2] = S[2, 0] + _tmp2 * dt
    _Snext[3] = S[3, 0] * _tmp11 + _tmp10 * _tmp3 - _tmp12 * _tmp6 + _tmp13 * _tmp5
    _Snext[4] = S[4, 0] * _tmp11 + _tmp12 * _tmp5 + _tmp13 * _tmp6 - _tmp14 * _tmp3
    _Snext[5] = S[5, 0] * _tmp11 - _tmp10 * _tmp5 + _tmp13 * _tmp3 + _tmp14 * _tmp6
    _Snext[6] = S[6, 0] * _tmp11 - _tmp10 * _tmp6 - _tmp12 * _tmp3 - _tmp14 * _tmp5
    _Snext[7] = _tmp0
    _Snext[8] = _tmp1
    _Snext[9] = _tmp2
    _Snext[10] = _tmp5
    _Snext[11] = _tmp6
    _Snext[12] = _tmp3
    return _Snext
