# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

from __future__ import annotations

import math
import typing as T

import numpy

import sym


def robot_state_update_jacobian(
    S: numpy.ndarray, gx_n: float, gy_n: float, gz_n: float, dt: float, epsilon: float
) -> numpy.ndarray:
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        S: Matrix13_1
        gx_n: Scalar
        gy_n: Scalar
        gz_n: Scalar
        dt: Scalar
        epsilon: Scalar

    Outputs:
        F: Matrix13_13
    """

    # Total ops: 202

    # Input arrays
    if S.shape == (13,):
        S = S.reshape((13, 1))
    elif S.shape != (13, 1):
        raise IndexError(
            "S is expected to have shape (13, 1) or (13,); instead had shape {}".format(S.shape)
        )

    # Intermediate terms (70)
    _tmp0 = dt**2
    _tmp1 = S[10, 0] + dt * gx_n
    _tmp2 = _tmp1**2
    _tmp3 = S[12, 0] + dt * gz_n
    _tmp4 = _tmp3**2
    _tmp5 = S[11, 0] + dt * gy_n
    _tmp6 = _tmp5**2
    _tmp7 = _tmp0 * _tmp2 + _tmp0 * _tmp4 + _tmp0 * _tmp6 + epsilon**2
    _tmp8 = math.sqrt(_tmp7)
    _tmp9 = (1.0 / 2.0) * _tmp8
    _tmp10 = math.cos(_tmp9)
    _tmp11 = math.sin(_tmp9)
    _tmp12 = _tmp11 / _tmp8
    _tmp13 = _tmp12 * dt
    _tmp14 = _tmp13 * _tmp3
    _tmp15 = -_tmp14
    _tmp16 = _tmp13 * _tmp5
    _tmp17 = _tmp1 * _tmp13
    _tmp18 = -_tmp17
    _tmp19 = -_tmp16
    _tmp20 = (1.0 / 2.0) * _tmp0 * _tmp12
    _tmp21 = _tmp1 * _tmp20
    _tmp22 = dt**3
    _tmp23 = _tmp11 / _tmp7 ** (3.0 / 2.0)
    _tmp24 = _tmp22 * _tmp23
    _tmp25 = S[5, 0] * _tmp24
    _tmp26 = _tmp1 * _tmp5
    _tmp27 = _tmp25 * _tmp26
    _tmp28 = (1.0 / 2.0) * _tmp10 / _tmp7
    _tmp29 = _tmp22 * _tmp28
    _tmp30 = S[5, 0] * _tmp29
    _tmp31 = _tmp26 * _tmp30
    _tmp32 = S[4, 0] * _tmp24
    _tmp33 = _tmp1 * _tmp3
    _tmp34 = _tmp32 * _tmp33
    _tmp35 = S[6, 0] * _tmp13
    _tmp36 = S[6, 0] * _tmp22
    _tmp37 = _tmp28 * _tmp36
    _tmp38 = _tmp23 * _tmp36
    _tmp39 = S[4, 0] * _tmp29
    _tmp40 = _tmp33 * _tmp39
    _tmp41 = S[5, 0] * _tmp13
    _tmp42 = S[3, 0] * _tmp24
    _tmp43 = S[3, 0] * _tmp29
    _tmp44 = _tmp33 * _tmp42 - _tmp33 * _tmp43
    _tmp45 = _tmp26 * _tmp37 - _tmp26 * _tmp38
    _tmp46 = S[4, 0] * _tmp13
    _tmp47 = -_tmp46
    _tmp48 = _tmp42 * _tmp5
    _tmp49 = _tmp1 * _tmp48
    _tmp50 = _tmp26 * _tmp43
    _tmp51 = _tmp33 * _tmp37 - _tmp33 * _tmp38
    _tmp52 = S[3, 0] * _tmp13
    _tmp53 = -_tmp52
    _tmp54 = _tmp25 * _tmp33
    _tmp55 = _tmp30 * _tmp33
    _tmp56 = _tmp26 * _tmp32 - _tmp26 * _tmp39
    _tmp57 = -_tmp41
    _tmp58 = S[3, 0] * _tmp20
    _tmp59 = _tmp3 * _tmp5
    _tmp60 = _tmp32 * _tmp59
    _tmp61 = _tmp39 * _tmp59
    _tmp62 = S[4, 0] * _tmp20
    _tmp63 = _tmp43 * _tmp59
    _tmp64 = _tmp3 * _tmp48
    _tmp65 = S[5, 0] * _tmp20
    _tmp66 = _tmp37 * _tmp59 - _tmp38 * _tmp59
    _tmp67 = S[6, 0] * _tmp20
    _tmp68 = _tmp25 * _tmp59 - _tmp30 * _tmp59
    _tmp69 = _tmp36 * _tmp4

    # Output terms
    _F = numpy.zeros((13, 13))
    _F[0, 0] = 1
    _F[1, 0] = 0
    _F[2, 0] = 0
    _F[3, 0] = 0
    _F[4, 0] = 0
    _F[5, 0] = 0
    _F[6, 0] = 0
    _F[7, 0] = 0
    _F[8, 0] = 0
    _F[9, 0] = 0
    _F[10, 0] = 0
    _F[11, 0] = 0
    _F[12, 0] = 0
    _F[0, 1] = 0
    _F[1, 1] = 1
    _F[2, 1] = 0
    _F[3, 1] = 0
    _F[4, 1] = 0
    _F[5, 1] = 0
    _F[6, 1] = 0
    _F[7, 1] = 0
    _F[8, 1] = 0
    _F[9, 1] = 0
    _F[10, 1] = 0
    _F[11, 1] = 0
    _F[12, 1] = 0
    _F[0, 2] = 0
    _F[1, 2] = 0
    _F[2, 2] = 1
    _F[3, 2] = 0
    _F[4, 2] = 0
    _F[5, 2] = 0
    _F[6, 2] = 0
    _F[7, 2] = 0
    _F[8, 2] = 0
    _F[9, 2] = 0
    _F[10, 2] = 0
    _F[11, 2] = 0
    _F[12, 2] = 0
    _F[0, 3] = 0
    _F[1, 3] = 0
    _F[2, 3] = 0
    _F[3, 3] = _tmp10
    _F[4, 3] = _tmp15
    _F[5, 3] = _tmp16
    _F[6, 3] = _tmp18
    _F[7, 3] = 0
    _F[8, 3] = 0
    _F[9, 3] = 0
    _F[10, 3] = 0
    _F[11, 3] = 0
    _F[12, 3] = 0
    _F[0, 4] = 0
    _F[1, 4] = 0
    _F[2, 4] = 0
    _F[3, 4] = _tmp14
    _F[4, 4] = _tmp10
    _F[5, 4] = _tmp18
    _F[6, 4] = _tmp19
    _F[7, 4] = 0
    _F[8, 4] = 0
    _F[9, 4] = 0
    _F[10, 4] = 0
    _F[11, 4] = 0
    _F[12, 4] = 0
    _F[0, 5] = 0
    _F[1, 5] = 0
    _F[2, 5] = 0
    _F[3, 5] = _tmp19
    _F[4, 5] = _tmp17
    _F[5, 5] = _tmp10
    _F[6, 5] = _tmp15
    _F[7, 5] = 0
    _F[8, 5] = 0
    _F[9, 5] = 0
    _F[10, 5] = 0
    _F[11, 5] = 0
    _F[12, 5] = 0
    _F[0, 6] = 0
    _F[1, 6] = 0
    _F[2, 6] = 0
    _F[3, 6] = _tmp17
    _F[4, 6] = _tmp16
    _F[5, 6] = _tmp14
    _F[6, 6] = _tmp10
    _F[7, 6] = 0
    _F[8, 6] = 0
    _F[9, 6] = 0
    _F[10, 6] = 0
    _F[11, 6] = 0
    _F[12, 6] = 0
    _F[0, 7] = dt
    _F[1, 7] = 0
    _F[2, 7] = 0
    _F[3, 7] = 0
    _F[4, 7] = 0
    _F[5, 7] = 0
    _F[6, 7] = 0
    _F[7, 7] = 1
    _F[8, 7] = 0
    _F[9, 7] = 0
    _F[10, 7] = 0
    _F[11, 7] = 0
    _F[12, 7] = 0
    _F[0, 8] = 0
    _F[1, 8] = dt
    _F[2, 8] = 0
    _F[3, 8] = 0
    _F[4, 8] = 0
    _F[5, 8] = 0
    _F[6, 8] = 0
    _F[7, 8] = 0
    _F[8, 8] = 1
    _F[9, 8] = 0
    _F[10, 8] = 0
    _F[11, 8] = 0
    _F[12, 8] = 0
    _F[0, 9] = 0
    _F[1, 9] = 0
    _F[2, 9] = dt
    _F[3, 9] = 0
    _F[4, 9] = 0
    _F[5, 9] = 0
    _F[6, 9] = 0
    _F[7, 9] = 0
    _F[8, 9] = 0
    _F[9, 9] = 1
    _F[10, 9] = 0
    _F[11, 9] = 0
    _F[12, 9] = 0
    _F[0, 10] = 0
    _F[1, 10] = 0
    _F[2, 10] = 0
    _F[3, 10] = (
        -S[3, 0] * _tmp21
        + _tmp2 * _tmp37
        - _tmp2 * _tmp38
        + _tmp27
        - _tmp31
        - _tmp34
        + _tmp35
        + _tmp40
    )
    _F[4, 10] = -S[4, 0] * _tmp21 - _tmp2 * _tmp25 + _tmp2 * _tmp30 + _tmp41 + _tmp44 + _tmp45
    _F[5, 10] = (
        -S[5, 0] * _tmp21 + _tmp2 * _tmp32 - _tmp2 * _tmp39 + _tmp47 - _tmp49 + _tmp50 + _tmp51
    )
    _F[6, 10] = (
        -S[6, 0] * _tmp21 + _tmp2 * _tmp42 - _tmp2 * _tmp43 + _tmp53 + _tmp54 - _tmp55 + _tmp56
    )
    _F[7, 10] = 0
    _F[8, 10] = 0
    _F[9, 10] = 0
    _F[10, 10] = 1
    _F[11, 10] = 0
    _F[12, 10] = 0
    _F[0, 11] = 0
    _F[1, 11] = 0
    _F[2, 11] = 0
    _F[3, 11] = _tmp25 * _tmp6 - _tmp30 * _tmp6 + _tmp45 - _tmp5 * _tmp58 + _tmp57 - _tmp60 + _tmp61
    _F[4, 11] = (
        -_tmp27
        + _tmp31
        + _tmp35
        + _tmp37 * _tmp6
        - _tmp38 * _tmp6
        - _tmp5 * _tmp62
        - _tmp63
        + _tmp64
    )
    _F[5, 11] = -_tmp42 * _tmp6 + _tmp43 * _tmp6 - _tmp5 * _tmp65 + _tmp52 + _tmp56 + _tmp66
    _F[6, 11] = _tmp32 * _tmp6 - _tmp39 * _tmp6 + _tmp47 + _tmp49 - _tmp5 * _tmp67 - _tmp50 + _tmp68
    _F[7, 11] = 0
    _F[8, 11] = 0
    _F[9, 11] = 0
    _F[10, 11] = 0
    _F[11, 11] = 1
    _F[12, 11] = 0
    _F[0, 12] = 0
    _F[1, 12] = 0
    _F[2, 12] = 0
    _F[3, 12] = -_tmp3 * _tmp58 - _tmp32 * _tmp4 + _tmp39 * _tmp4 + _tmp46 + _tmp51 + _tmp68
    _F[4, 12] = (
        -_tmp3 * _tmp62 + _tmp4 * _tmp42 - _tmp4 * _tmp43 + _tmp53 - _tmp54 + _tmp55 + _tmp66
    )
    _F[5, 12] = (
        -_tmp23 * _tmp69
        + _tmp28 * _tmp69
        - _tmp3 * _tmp65
        + _tmp34
        + _tmp35
        - _tmp40
        + _tmp63
        - _tmp64
    )
    _F[6, 12] = _tmp25 * _tmp4 - _tmp3 * _tmp67 - _tmp30 * _tmp4 + _tmp44 + _tmp57 + _tmp60 - _tmp61
    _F[7, 12] = 0
    _F[8, 12] = 0
    _F[9, 12] = 0
    _F[10, 12] = 0
    _F[11, 12] = 0
    _F[12, 12] = 1
    return _F
